VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ICustomPanelContentManager"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Private Const CLASS_NAME As String = "ICustomPanelContentManager"
'----------------------------------------------------------------------------------------------------------

Public Sub renderContent()
End Sub

Public Sub handleAfterResize()
End Sub

Public Sub handleAfterMove()
End Sub
