Attribute VB_Name = "modConst"
Option Explicit

Private Const CLASS_NAME As String = "modConst"
'----------------------------------------------------------------------------------------------------------
Public Const FILE_VERSION As String = "1.0.0"
'[Event messages] -----------------------------------------------------------------------------------------
'Public Const EVENT_CHANGE As String = "change"
'Public Const EVENT_CLICK As String = "click"
'Public Const EVENT_KEY_PRESSED As String = "key-pressed"
'Public Const EVENT_MOUSE_UP As String = "mouse-up"
Public Const EVENT_AFTER_VALIDATION As String = "after-validation"
Public Const EVENT_LAYOUT_CHANGE As String = "layout-change"
'[Actions] ------------------------------------------------------------------------------------------------
Public Const ACTION_ADD As String = "INSERT"
Public Const ACTION_DELETE As String = "DELETE"
Public Const ACTION_EDIT As String = "UPDATE"
Public Const ACTION_EXPORT_TO_EXCEL As String = "export-to-excel"
Public Const ACTION_FILTER_EDIT As String = "filter-edit"
Public Const ACTION_FILTER_OFF As String = "filter-off"
Public Const ACTION_FILTER_ON As String = "filter-on"
Public Const ACTION_INSERT As String = "INSERT"
Public Const ACTION_SORT As String = "sort"
'[Tags] ---------------------------------------------------------------------------------------------------
Public Const TAG_ACTION_PARAMS As String = "action-params"
Public Const TAG_ACTION_WHEN_VALID As String = "action-when-valid"
Public Const TAG_BUTTON As String = "button"
Public Const TAG_CANCEL As String = "cancel"
Public Const TAG_CAPTION As String = "caption"
Public Const TAG_CHANGE_CALLBACK As String = "change-callback"
Public Const TAG_COLUMN As String = "column"
Public Const TAG_CONFIRM As String = "confirm"
Public Const TAG_CONFIRM_WITH_ENTER As String = "confirm-with-enter"
Public Const TAG_CONTROL_TYPE As String = "control-type"
Public Const TAG_FILTER As String = "filter"
Public Const TAG_FUNCTION_NAME As String = "function"
Public Const TAG_ID As String = "id"
Public Const TAG_IS_LOCKED As String = "is-locked"
Public Const TAG_ITEM As String = "item"
Public Const TAG_ITEMS As String = "items"
'Public Const Props.KeyCode.getName As String = "key"
Public Const TAG_METHOD_INVOKER As String = "method-invoker"
Public Const TAG_METHOD_NAME As String = "method-name"
Public Const TAG_METHOD_PARAMS As String = "method-params"
Public Const TAG_NUMBER_FORMAT As String = "number-format"
Public Const TAG_OK As String = "ok"
Public Const TAG_ORDER As String = "order"
Public Const TAG_PARENT As String = "parent"
Public Const TAG_PICTURE As String = "picture"
Public Const TAG_PROPERTY As String = "property"
Public Const TAG_READ_ONLY As String = "read-only"
Public Const TAG_SAVE As String = "save"
Public Const TAG_SETTINGS As String = "settings"
'Public Const Props.Shift.getName As String = "shift"
Public Const TAG_STEP As String = "step"
Public Const TAG_START As String = "start"
Public Const TAG_TEXT_ALIGN As String = "text-align"
Public Const TAG_UPDATE_VIEW As String = "update-view"
Public Const TAG_VALIDATION_LINKS As String = "ValidationLinks"
Public Const TAG_VALIDATION_FUNCTION As String = "ValidationFunction"
Public Const TAG_VALIDATION_PARAMS As String = "ValidationParams"
Public Const TAG_VALIDATION_WIDTH As String = "ValidationWidth"
Public Const TAG_VALUES As String = "values"
Public Const TAG_VISIBILITY_PROPERTY As String = "visibility-property"
Public Const TAG_WINDOW As String = "window"
Public Const TAG_X As String = "x"
Public Const TAG_Y As String = "y"
'[UI property tags] ---------------------------------------------------------------------------------------
Public Const UI_PROP_PICTURE As String = "picture"
Public Const UI_PROP_WIDTH As String = "width"
Public Const UI_PROP_HEIGHT As String = "height"
Public Const UI_PROP_TOP As String = "top"
Public Const UI_PROP_LEFT As String = "left"
Public Const UI_PROP_ACTION_NAME As String = "actionName"
Public Const UI_PROP_TOOLTIP As String = "tooltip"
'----------------------------------------------------------------------------------------------------------
