VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IProjectCreatorProcessUnit"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Private Const CLASS_NAME As String = "IProjectCreatorProcessUnit"
'----------------------------------------------------------------------------------------------------------

Public Sub setParent(value As ProjectCreator)
End Sub
'
'Public Sub run(ByRef message As String, ByRef warnings As VBA.Collection, ByRef errors As VBA.Collection)
'End Sub
