VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IRepoManager"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Private Const CLASS_NAME As String = "IRepoManager"
'----------------------------------------------------------------------------------------------------------

Public Function getName() As String
End Function

Public Function setRepo(value As Repository2) As IRepoManager
End Function

Public Sub show()
End Sub

Public Sub destroy()
End Sub

Public Sub updateValues()
End Sub
