VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IStandarizerParent"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Private Const CLASS_NAME As String = "IStandarizerParent"
'----------------------------------------------------------------------------------------------------------

Public Function createNewItem() As IAliasable
End Function

'Public Function getItems(keyProperty As String) As Scripting.Dictionary
Public Function getItems() As Scripting.Dictionary
End Function
