VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IActionLogger"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Private Const CLASS_NAME As String = "IActionLogger"
'----------------------------------------------------------------------------------------------------------

Public Sub addLog(action As String, Optional params As Variant, Optional forceLog As Boolean = False)
End Sub
