VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IConfigurable"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

'Contains classes that can be configured with .json files.

Private Const CLASS_NAME As String = "IConfigurable"
'----------------------------------------------------------------------------------------------------------

Public Function getValue(propName As String) As Variant
End Function
